script:
  - date > lastbuild && git add lastbuild && git commit -m "Build - $(date)"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master