language: ruby
# only run CI-builds on master branch
branches:
  only:
  - master
rvm:
- 2.2.3
# set execution permission on our build script
before_script:
 - chmod +x ./ci-build.sh
# path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./ci-build.sh
exclude: [vendor]
sudo: false